### ISSUE TITLE
Add `conan` to Pip dependencies

### ISSUE THREAD

**Issue by jfoshee** [thejohnfreeman/cupcake.py#7]
So that using `pip` or `pipx` to install Cupcake also causes Conan to be installed.

Currently, if the user installs cupcake then runs `cupcake new`, `cupcake build`, they get:

```
FileNotFoundError: [Errno 2] No such file or directory: 'conan'
```

**Comment by thejohnfreeman** [comment]
This can't be done because it fixes a specific version of Conan, while Cupcake is meant to support any recent version of Conan, including both 1.x and 2.x. I'll include instructions to install Conan though.
